[package]
name = "aoc25-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
num = "0.4.3"
partitions = { version = "0.2.4", default-features = false, features = ["compact"] }
petgraph = "0.8.3"
regex = "1"
